package shared.events;

import shared.events.explorerEvents.GetMainTweetsEvent;
import shared.events.explorerEvents.SearchAccountEvent;
import shared.events.generalEvents.*;
import shared.events.messagingEvents.general.*;
import shared.events.messagingEvents.group.*;
import shared.events.messagingEvents.multiple.*;
import shared.events.messagingEvents.pv.*;
import shared.events.personalEvents.*;
import shared.events.personalEvents.notification.*;
import shared.events.settingEvents.*;
import shared.events.timelineEvents.*;
import shared.formEvents.LoginFormEvent;
import shared.formEvents.RegistrationFormEvent;
import shared.responses.Response;

public interface EventVisitor {
    Response registration (RegistrationFormEvent registrationFormEvent);
    Response login (LoginFormEvent loginFormEvent);
    Response accountActivation (AccountActivationEvent accountActivationEvent);
    Response changePassword (ChangePasswordEvent changePasswordEvent);
    Response deleteAccount(DeleteAccountEvent deleteAccountEvent);
    Response changeGeneralPrivacy(GeneralPrivacyEvent generalPrivacyEvent);
    Response changeItemPrivacy (ItemPrivacyEvent itemPrivacyEvent);
    Response lastSeen (LastSeenEvent lastSeenEvent);
    Response loadBlacklist (LoadBlacklistEvent loadBlacklistEvent);
    Response loadFollowers (LoadFollowersEvent loadFollowersEvent);
    Response loadFollowings (LoadFollowingsEvent loadFollowingsEvent);
    Response changeFirstName (ChangeFirstNameEvent changeFirstNameEvent);
    Response changeLastName (ChangeLastNameEvent changeLastNameEvent);
    Response unfollow (UnfollowUserEvent unfollowUserEvent);
    Response unblock (UnblockUserEvent unblockUserEvent);
    Response loadMyTweets (LoadMyTweetsEvent loadMyTweetsEvent);
    Response loadMyRequests (LoadMyRequestsEvent loadMyRequestsEvent);
    Response loadNewRequests (LoadNewRequestsEvent loadNewRequestsEvent);
    Response loadFollowingState (LoadFollowingStateEvent loadFollowingStateEvent);
    Response answerRequest (AnswerRequestEvent answerRequestEvent);
    Response deleteSeenNotifications (DeleteSeenNotificationsEvent deleteSeenNotificationsEvent);
    Response blockWriter (BlockWriterEvent blockWriterEvent);
    Response forwardTweet (ForwardTweetEvent forwardTweetEvent);
    Response likeOrDislike (LikeOrDislikeTweetEvent likeOrDislikeTweetEvent);
    Response loadComments (LoadCommentsEvent loadCommentsEvent);
    Response muteWriter (MuteWriterEvent muteWriterEvent);
    Response reportTweet (ReportTweetEvent reportTweetEvent);
    Response resendTweet (ResendTweetEvent resendTweetEvent);
    Response saveTweet (SaveTweetEvent saveTweetEvent);
    Response writeComment (WriteCommentEvent writeCommentEvent);
    Response getFirstTweetSeries (GetFirstTweetSeriesEvent getFirstTweetSeriesEvent);
    Response deleteMessage (DeleteMessageEvent deleteMessageEvent);
    Response editMessage (EditMessageEvent editMessageEvent);
    Response loadAllGroups (LoadAllGroupsEvent loadAllGroupsEvent);
    Response loadMyUser (LoadMyUserEvent loadMyUserEvent);
    Response loadUsernamesAndUnreadMessages (LoadUsernamesAndUnreadMessagesEvent loadUsernamesAndUnreadMessagesEvent);
    Response searchForMessage (SearchForMessageEvent searchForMessageEvent);
    Response addMemberToGroup (AddMemberToGroupEvent addMemberToGroupEvent);
    Response loadMessage (LoadMessagesEvent loadMessagesEvent);
    Response loadUsers (LoadUsersEvent loadUsersEvent);
    Response messageShown (MessageShownEvent messageShownEvent);
    Response writeNewMessageInGroup (WriteNewMessageInGroupEvent writeNewMessageInGroupEvent);
    Response addMemberToCategory (AddMemberToCategoryEvent addMemberToCategoryEvent);
    Response createNewCategoryName (CreateNewCategoryNameEvent createNewCategoryNameEvent);
    Response removeCategory (RemoveCategoryEvent removeCategoryEvent);
    Response removeMemberFromCategory (RemoveMemberFromCategoryEvent removeMemberFromCategoryEvent);
    Response sendMessageToGroup (SendMessageToGroupEvent sendMessageToGroupEvent);
    Response startMultipleMessaging (StartMultipleMessagingEvent startMultipleMessagingEvent);
    Response startSavedMessages (StartSavedMessagesEvent startSavedMessagesEvent);
    Response writeMessageInPV (WriteMessageInPVEvent writeMessageInPVEvent);
    Response writeMessageInSavedMessages (WriteMessageInSavedMessagesEvent writeMessageInSavedMessagesEvent);
    Response createNewGroup (CreateNewGroupEvent createNewGroupEvent);
    Response getMainTweets (GetMainTweetsEvent getMainTweetsEvent);
    Response loadImage (LoadImageEvent loadImageEvent);
    Response uploadProfileImage (UploadProfileImageEvent uploadProfileImageEvent);
    Response writeNewTweet(WriteNewTweetEvent writeNewTweetEvent);
    Response loadSaveMessagesPane(LoadSaveMessagePaneEvent loadSaveMessagePaneEvent);
    Response searchAccount (SearchAccountEvent searchAccountEvent);
    Response blockUser (BlockUserEvent blockUserEvent);
    Response followUser (FollowUserEvent followUserEvent);
    Response muteUser (MuteUserEvent muteUserEvent);
    Response updateProfile (UpdateProfileDetailsEvent updateProfileDetailsEvent);
    Response showMyInfo (ShowMyInfoEvent showMyInfoEvent);
    Response loadMessagesInPV (LoadMessagesInPVEvent loadMessagesInPVEvent);
    Response logOut (LogOutEvent logOutEvent);
    Response leaveGroup (LeaveGroupEvent leaveGroupEvent);
    Response writeScheduledMessageInGroup (WriteScheduledMessageInGroupEvent writeScheduledMessageInGroupEvent);
}
